package com.example.bricoli.enums;

public enum Type_service {
    electricien,
    Plombier,
            Menuisier,
    Jardinier,
            Serrurier,
    Vitrier,
            Ferronnier,
    Carreleur,
            Parqueteur,
    Chauffagiste,
            Couvreur,
    Plaquiste,
            Charpentier,
    Platrier,
    Poseur_fenetres,
            Antenniste,
    Monteur_meubles,

    Installateur_climatisation,
    Poseur_moquettes,
    Installateur_cuisines,
    Poseur_portes_volets,
    Monteur_pergolas_vérandas,
    Monteur_panneaux_solaires,
    Poseur_cloisons_seches,
    Paysagiste,
    Poseur_de_clotures,
    Installateur_systèmes_sécurité,
            Traiteur,
    Agent_sécurité,
            Chauffeur,
    Nounou,
            Bonne,
    Agent_ménage,
            Livreur,

    }
